name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  test-google-api:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: |
        cd google-api-tests
        npm install
        npm run test:ci
        npm run test:report

    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./google-api-tests/reports/cucumber_report.html
