name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  test-google-api:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - run: cd google-api-tests && npm install && npm run test:ci
    
    - name: Upload Google API report
      uses: actions/upload-artifact@v4
      with:
        name: google-api-report
        path: google-api-tests/reports/cucumber_report.html
